- include: firewalld.yml

- name: Configure firewall
  firewall_lib:
    zone: "{{ item.zone | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    forward_port: "{{ item.forward_port | default(omit) }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ firewall }}"
  register: firewall_lib_result
